---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install python-apt and apache2
    ansible.builtin.package:
      name:
      - python3-apt
      - apache2
      state: latest
  - name: Copy apache2.conf file
    ansible.builtin.copy:
      src: files/config/apache2.conf
      dest: /etc/apache2/sites-available/apache2.conf
      owner: root
      group: root
      mode: 0644
  - name: Copy index.html file
    ansible.builtin.copy:
      src: files/site/index.html
      dest: /var/www/html/index.html
      owner: www-data
      group: www-data
      mode: 0644
  - name: Enable Apache site by creating sympolic link
    ansible.builtin.file:
      src: /etc/apache2/sites-available/apache2.conf
      dest: /etc/apache2/sites-enabled/apache2.conf
      state: link
  - name: Restart apache2 service
    ansible.builtin.service:
      name: apache2
      state: restarted
